# Generated by Django 2.2 on 2021-01-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0002_auto_20210121_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='title',
        ),
    ]
