# Generated by Django 2.2 on 2021-01-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0003_auto_20210121_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='style',
        ),
    ]
