# Generated by Django 2.2 on 2021-01-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0004_remove_tag_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='style',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
