# Generated by Django 2.2 on 2021-01-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0005_tag_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='appy/'),
        ),
    ]
