# Generated by Django 2.2 on 2021-01-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0010_auto_20210125_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
    ]
