# Generated by Django 2.2 on 2021-01-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0011_remove_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
