# Generated by Django 2.2 on 2021-01-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0013_shoplist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
