# Generated by Django 2.2 on 2021-02-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0020_auto_20210205_2225'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique follows'),
        ),
    ]
