jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r foodpro/requirements.txt
      - name: "Lint with flake8"
        run: "flake8 --exclude foodpro/foodpro/settings.py, foodpro/foodpro/urls.py"
  name: lafoodies_workflow
  true:
    - push

  build_and_push_to_docker_hub:
    name: "Push Docker image to Docker Hub"
    needs: tests
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Check out the repo"
        uses: actions/checkout@v2
      - 
        name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - 
        name: "Login to Docker"
        uses: docker/login-action@v1
        with: 
          password: "${{ secrets.DOCKER_PASSWORD }}"
          username: "${{ secrets.DOCKER_USERNAME }}"
      - 
        name: "Push to Docker Hub"
        uses: docker/build-push-action@v2
        with: 
          push: true
          tags: "daero3333/foodpro:latest"
  deploy: 
    needs: build_and_push_to_docker_hub
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "executing remote ssh commands to deploy"
        uses: appleboy/ssh-action@master
        with: 
          host: "${{ secrets.HOST }}"
          key: "${{ secrets.SSH_KEY }}"
          passphrase: "${{ secrets.PASSPHRASE }}"
          script: |
              sudo docker pull daero3333/foodpro:latest
              sudo docker-compose stop
              sudo docker-compose rm web
              sudo docker-compose up -d
          username: "${{ secrets.USER }}"
