version: '3.3'

volumes:
  postgres_data:
  staticfiles:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: daero3333/gates:v1.0
    volumes:
      - staticfiles:/code/static
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.6
    depends_on:
      - web
    volumes:
      - staticfiles:/static
      - ./host.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8888:80
